fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.12.0"
    ntp: "https://github.com/puppetlabs/puppetlabs-ntp.git"
    rspec_monitor: "https://github.com/pgomersbach/test-rspec_monitor.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    lvm: "https://github.com/puppetlabs/puppetlabs-lvm.git"

  symlinks:
    profile_rsyslog: "#{source_dir}"
